import pyautogui
from time import sleep
import pyperclip
for i in range(1):
        pyautogui.moveTo(2063,366, duration=1)
        pyautogui.leftClick(duration=0.5)
        pyautogui.typewrite('1')
        pyautogui.press('tab')
        pyautogui.hotkey('ctrl', 't')
        sleep(2)
        pyautogui.typewrite('Que horas sao?')
        sleep(3)
        pyautogui.press('enter')
        pyautogui.moveTo(2235,244, duration=1)
        sleep(1)
        pyautogui.tripleClick(duration=1)
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.hotkey('ctrl', 'w')
        pyautogui.hotkey('ctrl', 'v')
        pyautogui.press('tab')
        pyautogui.hotkey('ctrl', 't')
        pyautogui.typewrite('Que dia e hoje?')
        pyautogui.press('enter')
        pyautogui.moveTo(2257,295, duration=1)
        sleep(2)
        pyautogui.tripleClick(duration=1)
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.hotkey('ctrl', 'w')
        pyautogui.moveTo(2321,358, duration=1)
        pyautogui.leftClick(duration=0.5)
        pyautogui.hotkey('ctrl', 'v')