import pyautogui
from time import sleep
import pyperclip
 for i in range(1):
        #coletar os dados do chatgpt
        webbrowser.open('https://chatgpt.com')
        sleep(5)
        pyautogui.click(709,935, duration=0.5)
        pyautogui.typewrite('escolha um tema aleatorio e faça um roteiro apenas')
        pyautogui.typewrite(' com as falas em forma de texto para copi e colar sem ')
        pyautogui.typewrite(' so o tema deve ser interessante e chamar antecao para criar engajamento.')
        pyautogui.typewrite(' lembre-se de o roteiro deve ser apena para um pessoa, sem encenacao')
        pyautogui.typewrite(' deve ser um conteudo para postar em um canal no yt com informacoes uteis')
        pyautogui.press('enter')
        pyautogui.moveTo(827,690, duration=1)
        sleep(30)
        pyautogui.scroll(-100000)
        pyautogui.leftClick(825,941, duration=1)
        pyautogui.typewrite('tire as separações do roteiro e coloque em uma unica mensagem ')
        pyautogui.typewrite('sem nenhuma fala a mais que não seja do roteiro')
        pyautogui.press('enter')
        pyautogui.moveTo(827,690,duration=1)
        sleep(30)
        pyautogui.scroll(-100000)
        pyautogui.click(727,800, duration=1)
        sleep(1)
        pyautogui.click(726,645,duration=1)
        sleep(1)
        pyautogui.click(728,748,duration=1)
    #passando os dados para o veed
    for i in range(1):
        webbrowser.open('https://www.veed.io/tools/ai-video/text-to-video')
        sleep(5)
        pyautogui.click(753,664, duration=1)
        pyautogui.hotkey('ctrl', 'v')
        pyautogui.press('enter')
        sleep(120)
        pyautogui.click(1752,136,duration=1)
        sleep(5)
        pyautogui.click(426,956, duration=1)
        sleep(5)
        pyautogui.click(1780,133, duration=1)
        sleep(5)
        pyautogui.click(1564,819,duration=1)
        sleep(100)
        pyautogui.click(1393,597, duration=1)
        sleep(5)
        pyautogui.click(970,653, duration=1)
        sleep(30)
    #postar no yt
